# Default initial positions for the ur10 arm's ros2_control fake system
initial_positions:
  shoulder_pan_joint: 1.
  shoulder_lift_joint: -1.
  elbow_joint: 1.
  wrist_1_joint: 0.0
  wrist_2_joint: 1.
  wrist_3_joint: 0.0